name: CI Pipeline

on:
  push:
    branches: [ "main", "Deuda_Tecnica_Procesos" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuración de entorno (ejemplo con Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalación de dependencias
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build
      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider


      # 5. Unit Tests
      - name: Run unit tests
        run: npm test -- --coverage

      

      # 8. ChatOps (Notificación en Teams)
      - name: Notify Teams
        uses: skitionek/notify-microsoft-teams@v1
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "CI Pipeline"
          text: "✅ Pipeline completado en *${{ github.repository }}* para commit *${{ github.sha }}*"